force-app/main/apex-batcher/objects/Folio_Process_Request__e/Folio_Process_Request__e.object-meta.xml
<CustomObject>
    <description
  >Used to execute the folio processing - submitted by the batch job</description>
    <label>Folio Process Request</label>
    <pluralLabel>Folio Process Requests</pluralLabel>
</CustomObject>

force-app/main/apex-batcher/objects/Folio_Process_Request__e/fields/UserIds__c.field-meta.xml
<CustomField>
    <fullName>UserIds__c</fullName>
    <description
  >Comma separated list of user Ids to process, no spaces, max number 99</description>
    <label>UserIds</label>
    <length>1881</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/apex-batcher/classes/BatchByUsers.cls
// If there are more users than folios, we are batching by users
// We need to create sub-batches where the total number of users * folios per batch is less than 100

public with sharing class BatchByUsers implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful, Database.RaisesPlatformEvents {
  private List<Folio_Process_Request__e> folioRequests = new List<Folio_Process_Request__e>();

  public Database.QueryLocator start(Database.BatchableContext info) {
    String query = 'SELECT Id, Name FROM User WHERE IsActive = true';
    return Database.getQueryLocator(query);
  }

  public void execute(Database.BatchableContext info, List<SObject> scope) {
    List<User> users = (List<User>) scope;
    List<Id> userIds = new List<Id>();
    for (User u : users) {
      userIds.add(u.Id);
    }
    String userIdsCsv = String.join(userIds, ',');
    this.folioRequests.add(
      new Folio_Process_Request__e(UserIds__c = userIdsCsv)
    );
  }

  public void finish(Database.BatchableContext info) {
    // Finalization logic if needed
    EventBus.publish(this.folioRequests);
    System.debug('Batch By Users Finished.');
  }
}